# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Strawberry\c\bin\cmake.exe

# The command to remove a file.
RM = C:\Strawberry\c\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Dan Ovidiu\Documents\antigravity\keen-newton\powertrain_sil_network"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Dan Ovidiu\Documents\antigravity\keen-newton\powertrain_sil_network"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\Strawberry\c\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Strawberry\c\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Dan Ovidiu\Documents\antigravity\keen-newton\powertrain_sil_network\CMakeFiles" "C:\Users\Dan Ovidiu\Documents\antigravity\keen-newton\powertrain_sil_network\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Dan Ovidiu\Documents\antigravity\keen-newton\powertrain_sil_network\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named network_sil

# Build rule for target.
network_sil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 network_sil
.PHONY : network_sil

# fast build rule for target.
network_sil/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/build
.PHONY : network_sil/fast

Engine_vECU/engine.obj: Engine_vECU/engine.c.obj
.PHONY : Engine_vECU/engine.obj

# target to build an object file
Engine_vECU/engine.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Engine_vECU/engine.c.obj
.PHONY : Engine_vECU/engine.c.obj

Engine_vECU/engine.i: Engine_vECU/engine.c.i
.PHONY : Engine_vECU/engine.i

# target to preprocess a source file
Engine_vECU/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Engine_vECU/engine.c.i
.PHONY : Engine_vECU/engine.c.i

Engine_vECU/engine.s: Engine_vECU/engine.c.s
.PHONY : Engine_vECU/engine.s

# target to generate assembly for a file
Engine_vECU/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Engine_vECU/engine.c.s
.PHONY : Engine_vECU/engine.c.s

FMU_Plant/fmu_powertrain.obj: FMU_Plant/fmu_powertrain.c.obj
.PHONY : FMU_Plant/fmu_powertrain.obj

# target to build an object file
FMU_Plant/fmu_powertrain.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/FMU_Plant/fmu_powertrain.c.obj
.PHONY : FMU_Plant/fmu_powertrain.c.obj

FMU_Plant/fmu_powertrain.i: FMU_Plant/fmu_powertrain.c.i
.PHONY : FMU_Plant/fmu_powertrain.i

# target to preprocess a source file
FMU_Plant/fmu_powertrain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/FMU_Plant/fmu_powertrain.c.i
.PHONY : FMU_Plant/fmu_powertrain.c.i

FMU_Plant/fmu_powertrain.s: FMU_Plant/fmu_powertrain.c.s
.PHONY : FMU_Plant/fmu_powertrain.s

# target to generate assembly for a file
FMU_Plant/fmu_powertrain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/FMU_Plant/fmu_powertrain.c.s
.PHONY : FMU_Plant/fmu_powertrain.c.s

Transmission_vECU/transmission.obj: Transmission_vECU/transmission.c.obj
.PHONY : Transmission_vECU/transmission.obj

# target to build an object file
Transmission_vECU/transmission.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Transmission_vECU/transmission.c.obj
.PHONY : Transmission_vECU/transmission.c.obj

Transmission_vECU/transmission.i: Transmission_vECU/transmission.c.i
.PHONY : Transmission_vECU/transmission.i

# target to preprocess a source file
Transmission_vECU/transmission.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Transmission_vECU/transmission.c.i
.PHONY : Transmission_vECU/transmission.c.i

Transmission_vECU/transmission.s: Transmission_vECU/transmission.c.s
.PHONY : Transmission_vECU/transmission.s

# target to generate assembly for a file
Transmission_vECU/transmission.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Transmission_vECU/transmission.c.s
.PHONY : Transmission_vECU/transmission.c.s

Virtual_CAN/vcan.obj: Virtual_CAN/vcan.c.obj
.PHONY : Virtual_CAN/vcan.obj

# target to build an object file
Virtual_CAN/vcan.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Virtual_CAN/vcan.c.obj
.PHONY : Virtual_CAN/vcan.c.obj

Virtual_CAN/vcan.i: Virtual_CAN/vcan.c.i
.PHONY : Virtual_CAN/vcan.i

# target to preprocess a source file
Virtual_CAN/vcan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Virtual_CAN/vcan.c.i
.PHONY : Virtual_CAN/vcan.c.i

Virtual_CAN/vcan.s: Virtual_CAN/vcan.c.s
.PHONY : Virtual_CAN/vcan.s

# target to generate assembly for a file
Virtual_CAN/vcan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/Virtual_CAN/vcan.c.s
.PHONY : Virtual_CAN/vcan.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\network_sil.dir\build.make CMakeFiles/network_sil.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... network_sil
	@echo ... Engine_vECU/engine.obj
	@echo ... Engine_vECU/engine.i
	@echo ... Engine_vECU/engine.s
	@echo ... FMU_Plant/fmu_powertrain.obj
	@echo ... FMU_Plant/fmu_powertrain.i
	@echo ... FMU_Plant/fmu_powertrain.s
	@echo ... Transmission_vECU/transmission.obj
	@echo ... Transmission_vECU/transmission.i
	@echo ... Transmission_vECU/transmission.s
	@echo ... Virtual_CAN/vcan.obj
	@echo ... Virtual_CAN/vcan.i
	@echo ... Virtual_CAN/vcan.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

